-- Seed data for Dutch Wall Fort

-- Insert admin user (password: admin123)
-- Note: This is a bcrypt hash for 'admin123' - you should change this in production
INSERT INTO users (email, password, name, role) VALUES
('admin@dutchwallfort.com', '$2b$10$vZaPiDrNS0kGdODFMnQU6OOPDYLlqbaRBugYjwUoM0fLchF7BYMLW', 'Admin User', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Insert room data
INSERT INTO rooms (slug, name, short_description, long_description, capacity, beds, amenities, price, images, is_active) VALUES
('deluxe-family-room', 'Deluxe Family Room', 'Spacious family room with balcony and garden view', 'Our most spacious accommodation offers the perfect blend of comfort and charm for families visiting Galle Fort. The room features a comfortable double bed and two single beds, ensuring everyone has a restful night''s sleep. Step out onto your private balcony to enjoy garden views and the peaceful atmosphere of historic Church Street. The room maintains the villa''s Dutch colonial character while providing all modern amenities including air conditioning, private bathroom with shower, and complimentary Wi-Fi. The space includes a convenient work desk for those who need to stay connected, and the private entrance ensures your privacy and comfort throughout your stay.', 4, '1 double bed + 2 single beds', '["Air conditioning", "Private bathroom (shower)", "Complimentary breakfast", "Free Wi-Fi", "Private balcony", "Garden view", "Work desk", "Private entrance", "Daily housekeeping", "Safe"]', 15000.00, '["/images/bedroom1_1.jpg", "/images/bedroom1_2.jpg", "/images/bedroom1_3.jpg", "/images/bedroom1_4.jpg", "/images/bedroom1_5.jpg", "/images/bedroom1_6.jpg"]', true),
('superior-room', 'Superior Room', 'Comfortable room with private entrance and work area', 'The Superior Room offers an ideal balance of space, comfort, and privacy for couples or small families. Featuring a double bed and single bed, this room is perfect for those seeking a bit more space during their stay in Galle Fort. The room includes a dedicated work desk area, making it suitable for business travelers or digital nomads. Your private entrance ensures complete independence, while the modern amenities including air conditioning, private bathroom, and mini fridge add to your comfort. The room showcases beautiful Dutch colonial architectural details while providing contemporary conveniences for a memorable stay.', 3, '1 double bed + 1 single bed', '["Air conditioning", "Private bathroom (shower)", "Complimentary breakfast", "Free Wi-Fi", "Private entrance", "Work desk", "Mini fridge", "Daily housekeeping", "Safe", "Reading lights"]', 12000.00, '["/images/bedroom2_1.jpg", "/images/bedroom2_2.jpg", "/images/bedroom2_3.jpg", "/images/bedroom2_4.jpg", "/images/bedroom2_5.jpg"]', true),
('standard-room', 'Standard Room', 'Cozy room with all essential amenities', 'Our Standard Room may be cozy in size, but it''s generous in comfort and style. Perfect for couples seeking an intimate and comfortable base for exploring Galle Fort. The room features a comfortable double bed with quality linens, ensuring a good night''s rest after your adventures. Despite being our most compact option, the room includes all essential amenities including air conditioning, private bathroom, and complimentary breakfast. The space is thoughtfully designed to maximize comfort while maintaining the charm and character of our Dutch colonial villa. Daily housekeeping and a personal safe add to your peace of mind during your stay.', 2, '1 double bed', '["Air conditioning", "Private bathroom (shower)", "Complimentary breakfast", "Free Wi-Fi", "Daily housekeeping", "Safe", "Reading lights", "Wardrobe", "Mirror", "Electrical outlets"]', 9000.00, '["/images/bedroom3_1.jpg", "/images/bedroom3_2.jpg", "/images/bedroom3_3.jpg", "/images/bedroom3_4.jpg"]', true),
('premium-room', 'Premium Room', 'Premium Room — 2-3 guests, spacious with modern amenities', 'Our premium accommodation offers extra space and luxury amenities. Perfect for guests seeking additional comfort and style during their stay in Galle Fort. This spacious room features premium furnishings, a private balcony, and modern amenities that elevate your experience to the next level. Whether you''re celebrating a special occasion or simply want to indulge in the best our villa has to offer, the Premium Room provides an exceptional blend of comfort, style, and convenience. Enjoy the enhanced amenities including a mini bar, premium bedding, and additional space for relaxation or work.', 3, '1 double bed + 1 single bed', '["Air conditioning", "Private bathroom (shower)", "Private balcony", "Premium furnishings", "Mini bar", "Complimentary breakfast", "Free Wi-Fi", "Work desk", "Daily housekeeping", "Safe", "Room service"]', 18000.00, '["/images/bedroom4_1.jpg", "/images/bedroom4_2.jpg", "/images/bedroom4_3.jpg", "/images/bedroom4_4.jpg", "/images/bedroom4_5.jpg"]', true),
('whole-villa', 'Whole Villa Rental', 'Entire Villa — Up to 12 guests, all rooms included', 'Book the entire Dutch Wall Fort villa for your group, family reunion, or special celebration. This exclusive rental includes all four beautifully appointed rooms, common living areas, terrace, full kitchen access, and complete privacy for your group. Perfect for larger gatherings, corporate retreats, or anyone seeking an authentic Galle Fort experience with the luxury of an entire historic villa. Your group will enjoy private dining areas, multiple balconies, garden access, and personalized concierge service. The whole villa rental provides the ultimate in comfort and exclusivity, with dedicated staff ensuring your every need is met throughout your stay.', 12, '4 rooms: 3 double beds + 4 single beds', '["All 4 rooms included", "Exclusive villa access", "Full kitchen access", "Terrace & garden", "Multiple balconies", "Group breakfast service", "Concierge service", "Event planning assistance", "Private chef available", "Daily housekeeping", "Welcome amenities", "Airport transfers"]', 45000.00, '["/images/Exterior_1.jpg", "/images/livingroom.jpg", "/images/dining area_1.jpg", "/images/balcony_1.jpg", "/images/kitchen_1.jpg", "/images/Exterior_3.jpg", "/images/balcony_2.jpg"]', true)
ON CONFLICT (slug) DO NOTHING;

-- Insert services data
INSERT INTO services (slug, name, description, type, duration, price, features, is_active) VALUES
('galle-fort-walking-tour', 'Galle Fort Walking Tour', 'Comprehensive guided walking tour of historic Galle Fort, exploring Dutch colonial architecture, ancient ramparts, and hidden gems of this UNESCO World Heritage Site.', 'tours', '2-3 hours', 3000.00, '["Professional guide", "Historical insights", "Photo opportunities", "Local recommendations"]', true),
('southern-coast-day-tour', 'Southern Coast Day Tour', 'Explore the stunning southern coast including Unawatuna Beach, Jungle Beach, turtle hatchery, and local attractions.', 'tours', 'Full day', 8000.00, '["Transportation included", "Professional driver", "Multiple stops", "Flexible itinerary"]', true),
('yala-safari-tour', 'Yala National Park Safari', 'Experience Sri Lankas wildlife with a full-day safari tour to Yala National Park, home to leopards, elephants, and diverse bird species.', 'tours', 'Full day', 15000.00, '["4x4 safari vehicle", "Park entrance fees", "Breakfast", "Professional tracker", "Binoculars provided"]', true),
('airport-transfer', 'Airport Transfer Service', 'Comfortable and reliable transfer service between Colombo/Koggala airports and Dutch Wall Fort.', 'transport', 'One way', 8000.00, '["Air-conditioned vehicle", "Professional driver", "Door-to-door service", "Luggage assistance", "Flight tracking"]', true),
('vehicle-rental-with-driver', 'Vehicle Rental with Driver', 'Rent a comfortable vehicle with experienced local driver for your custom explorations around Galle and beyond.', 'transport', 'Per day (8 hours)', 12000.00, '["Experienced driver", "Fuel included", "Insurance covered", "Flexible itinerary", "English speaking driver"]', true),
('tuk-tuk-rental', 'Tuk-Tuk City Tours', 'Experience authentic Sri Lankan travel with a tuk-tuk and driver for exploring Galle Fort and nearby areas.', 'transport', 'Per day', 6000.00, '["Experienced driver", "Fuel included", "City tour route", "Fun experience"]', true),
('currency-exchange', 'Currency Exchange Service', 'Convenient money exchange service at competitive rates for major currencies.', 'services', 'Instant', 0.00, '["Competitive rates", "Major currencies accepted", "Secure transactions", "No hidden fees"]', true),
('laundry-service', 'Laundry Service', 'Professional laundry and dry cleaning service with same-day or next-day delivery.', 'services', '24-48 hours', 500.00, '["Same/next day service", "Professional cleaning", "Folded and pressed", "Per kg pricing"]', true)
ON CONFLICT (slug) DO NOTHING;

-- Insert sample blog post
INSERT INTO blog_posts (slug, title, excerpt, content, author_id, status, published_at) VALUES
('discover-galle-fort-guide', 'Discover Galle Fort: A Complete Guide', 'Everything you need to know about exploring this UNESCO World Heritage Site and its rich Dutch colonial history.',
'Galle Fort, located on the southwestern tip of Sri Lanka, is a living monument to the islands colonial past. Built first by the Portuguese in 1588, then extensively fortified by the Dutch during the 17th century, the fort stands as one of the best-preserved colonial fortresses in Asia.

## A Walk Through History

Walking through the cobblestone streets of Galle Fort is like stepping back in time. The massive ramparts, originally built to defend against invaders, now provide stunning views of the Indian Ocean and serve as a popular promenade for locals and tourists alike.

## Must-Visit Attractions

### The Ramparts
The fortifications stretch for 3km around the peninsula, offering breathtaking ocean views and the perfect spot for sunset watching.

### Dutch Reformed Church
Built in 1755, this historic church features beautiful old tombstones and a unique floor made of gravestones.

### Lighthouse
The iconic white lighthouse, built in 1938, has become a symbol of Galle Fort and offers spectacular photo opportunities.

### Museums
Visit the National Maritime Museum and the Historical Mansion Museum to learn about the forts rich history.

## Where to Stay

Dutch Wall Fort offers comfortable accommodation in the heart of the fort, providing easy access to all major attractions while maintaining the authentic character of this historic area.

## Best Time to Visit

Galle Fort can be visited year-round, but the best weather is typically from December to March. The fort is particularly magical during sunset when the golden light illuminates the ancient walls.',
(SELECT id FROM users WHERE email = 'admin@dutchwallfort.com' LIMIT 1),
'published',
CURRENT_TIMESTAMP)
ON CONFLICT (slug) DO NOTHING;

-- Insert sample reviews
INSERT INTO reviews (guest_name, rating, comment, is_approved) VALUES
('Sarah Johnson', 5, 'Absolutely wonderful stay at Dutch Wall Fort! The rooms are spacious and clean, and the location right in the heart of Galle Fort is perfect. The hosts were incredibly helpful with tour arrangements.', true),
('Michael Chen', 5, 'Best accommodation in Galle Fort! Beautiful colonial architecture, modern amenities, and exceptional service. The family room was perfect for our group of four.', true),
('Emma Williams', 4, 'Great location and comfortable rooms. The staff helped us arrange a fantastic day tour of the southern coast. Would definitely recommend to friends visiting Sri Lanka.', true)
ON CONFLICT DO NOTHING;

-- Insert sample bookings
INSERT INTO bookings (guest_name, guest_email, guest_phone, check_in, check_out, room_id, guests, message, status) VALUES
('John Smith', 'john.smith@email.com', '+1-555-0123', '2024-12-15', '2024-12-18', 1, 2, 'Looking forward to our stay in Galle Fort!', 'confirmed'),
('Maria Garcia', 'maria.garcia@email.com', '+44-20-7946-0958', '2024-12-20', '2024-12-23', 2, 3, 'Family vacation with our daughter. Please arrange airport pickup.', 'pending'),
('David Lee', 'david.lee@email.com', '+61-2-9374-4000', '2024-12-25', '2024-12-28', 3, 2, 'Anniversary trip. Would love a room with a view.', 'confirmed'),
('Anna Kowalski', 'anna.kowalski@email.com', '+48-22-123-4567', '2024-12-30', '2025-01-02', 4, 2, 'New Year celebration in Galle Fort!', 'pending'),
('Robert Brown', 'robert.brown@email.com', '+1-555-0456', '2025-01-05', '2025-01-10', 5, 12, 'Corporate retreat. Need the whole villa for our team.', 'confirmed')
ON CONFLICT DO NOTHING;

-- Insert sample testimonials
INSERT INTO testimonials (guest_name, guest_location, rating, title, content, is_featured, is_approved) VALUES
('Sarah & Michael Johnson', 'New York, USA', 5, 'Perfect Galle Fort Experience', 'Our stay at Dutch Wall Fort was absolutely magical! The historic charm combined with modern amenities made it the perfect base for exploring Galle Fort. The staff was incredibly welcoming and the breakfast was delicious. We can''t wait to return!', true, true),
('Emma Thompson', 'London, UK', 5, 'A Hidden Gem', 'What a beautiful property! The attention to detail in preserving the colonial architecture while providing modern comfort is remarkable. The balcony views are stunning, and the location right in the heart of Galle Fort is unbeatable. Highly recommended!', true, true),
('James & Lisa Chen', 'Melbourne, Australia', 5, 'Exceeded All Expectations', 'We booked the whole villa for our family reunion and it was perfect! Each room has its own character, the common areas are spacious, and the garden is lovely. The staff went above and beyond to make our stay special. Thank you for the memories!', true, true),
('Maria Rodriguez', 'Barcelona, Spain', 4, 'Charming and Authentic', 'Dutch Wall Fort offers an authentic Galle Fort experience. The rooms are beautifully decorated, the location is perfect for exploring, and the staff is very helpful. The only minor issue was the WiFi speed, but everything else was wonderful.', false, true),
('Ahmed Hassan', 'Dubai, UAE', 5, 'Outstanding Hospitality', 'From the moment we arrived, we felt welcomed and cared for. The property is stunning, the rooms are comfortable, and the breakfast is excellent. The staff helped us plan our Galle Fort itinerary and even arranged a tuk-tuk tour. Highly recommended!', false, true),
('Sophie & Pierre Dubois', 'Paris, France', 5, 'Magnifique!', 'Une expérience inoubliable dans le fort de Galle! L''architecture coloniale hollandaise est préservée avec goût, les chambres sont confortables et l''accueil est chaleureux. Nous recommandons vivement cette adresse.', false, true)
ON CONFLICT DO NOTHING;

-- Insert sample blog categories
INSERT INTO blog_categories (slug, name, description, color, is_active) VALUES
('travel-guides', 'Travel Guides', 'Comprehensive guides to exploring Galle Fort and surrounding areas', '#3B82F6', true),
('local-attractions', 'Local Attractions', 'Discover the best places to visit in and around Galle Fort', '#10B981', true),
('dining-recommendations', 'Dining & Food', 'Restaurant reviews and culinary experiences in Galle Fort', '#F59E0B', true),
('photography-tips', 'Photography', 'Tips and spots for capturing the beauty of Galle Fort', '#8B5CF6', true),
('cultural-insights', 'Culture & History', 'Learn about the rich history and culture of Galle Fort', '#EF4444', true),
('accommodation-tips', 'Accommodation', 'Tips and insights about staying in Galle Fort', '#06B6D4', true)
ON CONFLICT (slug) DO NOTHING;

-- Insert sample blog posts
INSERT INTO blog_posts (slug, title, excerpt, content, featured_image, author, is_published, published_at, category_id) VALUES
('discovering-galle-fort-unesco-heritage', 'Discovering Galle Fort: A UNESCO World Heritage Site', 'Explore the rich history and architectural beauty of Galle Fort, one of Sri Lanka''s most treasured UNESCO World Heritage Sites.', '<h2>The Historic Heart of Galle</h2><p>Galle Fort stands as a magnificent testament to Sri Lanka''s colonial past, where Portuguese, Dutch, and British influences have left their indelible mark on this coastal city. Built in 1588 by the Portuguese and later fortified by the Dutch in 1663, this UNESCO World Heritage Site is a living museum of colonial architecture and culture.</p><h3>Architectural Marvels</h3><p>Walking through the cobblestone streets of Galle Fort, you''ll encounter a fascinating blend of architectural styles. The Dutch colonial buildings with their characteristic gables, verandas, and courtyards create a unique urban landscape that has remained largely unchanged for centuries.</p><ul><li><strong>Dutch Reformed Church:</strong> Built in 1755, this historic church features beautiful stained glass windows and colonial architecture.</li><li><strong>Galle Lighthouse:</strong> One of the oldest lighthouses in Sri Lanka, offering stunning views of the Indian Ocean.</li><li><strong>Old Dutch Hospital:</strong> Now converted into a shopping and dining complex while preserving its historic facade.</li></ul><h3>Cultural Experiences</h3><p>Beyond its architectural beauty, Galle Fort is a vibrant cultural hub. The narrow streets are lined with boutique shops, art galleries, cafes, and restaurants that offer a taste of both traditional Sri Lankan culture and contemporary lifestyle.</p><p>Don''t miss the opportunity to visit the Galle Fort Museum, which houses artifacts from the Dutch period, or take a leisurely stroll along the ramparts at sunset for breathtaking views of the ocean.</p><h3>Staying in Galle Fort</h3><p>For the ultimate Galle Fort experience, consider staying within the fort walls. Our historic villa at Dutch Wall Fort offers an authentic colonial experience with modern amenities, allowing you to immerse yourself in the rich history and culture of this remarkable place.</p>', '/images/galle-fort-1.jpg', 'Dutch Wall Fort Team', true, NOW(), 1),
('best-local-restaurants-galle-fort', 'Best Local Restaurants in Galle Fort', 'Discover the culinary delights of Galle Fort with our guide to the best local restaurants, from traditional Sri Lankan cuisine to international flavors.', '<h2>Culinary Adventures in Galle Fort</h2><p>Galle Fort is not just a feast for the eyes but also a paradise for food lovers. The historic streets are home to some of Sri Lanka''s most innovative and traditional restaurants, offering everything from authentic local cuisine to international fusion dishes.</p><h3>Traditional Sri Lankan Cuisine</h3><p>For an authentic taste of Sri Lankan flavors, these restaurants are must-visits:</p><ul><li><strong>Heritage Cafe:</strong> Known for their traditional rice and curry, served in a beautiful colonial setting.</li><li><strong>Pedlar''s Inn Cafe:</strong> Offers a mix of local and international dishes with a focus on fresh, local ingredients.</li><li><strong>Fortaleza Restaurant:</strong> Specializes in traditional Sri Lankan seafood dishes with a modern twist.</li></ul><h3>International Flavors</h3><p>Galle Fort also offers excellent international dining options:</p><ul><li><strong>Chamber of Secrets:</strong> A rooftop restaurant with stunning ocean views and Mediterranean cuisine.</li><li><strong>Poonie''s Kitchen:</strong> Famous for their wood-fired pizzas and Italian dishes.</li><li><strong>Amangalla Hotel Restaurant:</strong> Fine dining experience with a mix of Sri Lankan and international cuisine.</li></ul><h3>Street Food and Cafes</h3><p>Don''t miss the local street food scene and charming cafes that dot the fort''s streets. From fresh fruit juices to traditional hoppers and kottu roti, there''s something to satisfy every palate.</p><p>Many of these establishments are housed in beautifully restored colonial buildings, adding to the unique dining experience that Galle Fort offers.</p>', '/images/galle-restaurants-1.jpg', 'Dutch Wall Fort Team', true, NOW() - INTERVAL ''1 day'', 3),
('galle-fort-shopping-guide', 'Shopping in Galle Fort: A Complete Guide', 'From traditional handicrafts to contemporary art, discover the best shopping spots in Galle Fort for unique souvenirs and local treasures.', '<h2>Treasure Hunting in Galle Fort</h2><p>Galle Fort is a shopper''s paradise, offering everything from traditional Sri Lankan handicrafts to contemporary art and jewelry. The narrow streets are lined with boutique shops, galleries, and markets that showcase the best of local craftsmanship and international design.</p><h3>Traditional Handicrafts</h3><p>For authentic Sri Lankan handicrafts, visit these renowned shops:</p><ul><li><strong>Laksala:</strong> Government-run store offering traditional handicrafts, textiles, and souvenirs.</li><li><strong>Barefoot:</strong> Famous for their handwoven textiles, clothing, and home decor items.</li><li><strong>Paradise Road Galleries:</strong> Features contemporary Sri Lankan art and design.</li></ul><h3>Jewelry and Accessories</h3><p>Galle Fort is home to several jewelry stores offering both traditional and contemporary pieces:</p><ul><li><strong>Amangalla Spa Shop:</strong> Luxury spa products and accessories.</li><li><strong>Local Artisan Shops:</strong> Handcrafted jewelry using traditional techniques and local materials.</li></ul><h3>Art Galleries</h3><p>The fort is a hub for contemporary art, with several galleries showcasing local and international artists:</p><ul><li><strong>Galle Fort Art Gallery:</strong> Features rotating exhibitions of contemporary Sri Lankan art.</li><li><strong>Rampart Gallery:</strong> Specializes in photography and mixed media art.</li></ul><h3>Shopping Tips</h3><p>When shopping in Galle Fort, remember to:</p><ul><li>Bargain politely - it''s part of the local culture</li><li>Look for authentic handicrafts with proper certification</li><li>Visit during weekdays for a more relaxed shopping experience</li><li>Ask about the story behind handmade items</li></ul><p>Many shops offer shipping services for larger items, making it easy to take your treasures home with you.</p>', '/images/galle-shopping-1.jpg', 'Dutch Wall Fort Team', true, NOW() - INTERVAL ''2 days'', 2),
('galle-fort-photography-spots', 'Photography Spots in Galle Fort: Capture the Perfect Shot', 'Discover the most photogenic locations in Galle Fort, from sunrise at the ramparts to golden hour in the colonial streets.', '<h2>Capturing Galle Fort Through Your Lens</h2><p>Galle Fort is a photographer''s dream, offering endless opportunities to capture stunning images of colonial architecture, vibrant street life, and breathtaking ocean views. Whether you''re a professional photographer or just love taking beautiful photos, these locations will provide the perfect backdrop for your shots.</p><h3>Sunrise and Sunset Spots</h3><p>The best times to photograph Galle Fort are during the golden hours:</p><ul><li><strong>Galle Lighthouse:</strong> Perfect for sunrise shots with the lighthouse silhouetted against the morning sky.</li><li><strong>Ramparts:</strong> Walk along the fort walls for panoramic ocean views and dramatic sunset shots.</li><li><strong>Flag Rock:</strong> A popular spot for sunset photography with locals and tourists gathering to watch the sun dip below the horizon.</li></ul><h3>Architectural Photography</h3><p>Galle Fort''s colonial architecture provides endless opportunities for architectural photography:</p><ul><li><strong>Dutch Reformed Church:</strong> Capture the beautiful colonial facade and interior details.</li><li><strong>Old Dutch Hospital:</strong> Now a shopping complex, but the exterior maintains its historic charm.</li><li><strong>Colonial Houses:</strong> The residential streets offer beautiful examples of Dutch colonial architecture.</li></ul><h3>Street Photography</h3><p>The vibrant street life of Galle Fort makes for excellent street photography:</p><ul><li><strong>Church Street:</strong> Bustling with shops, cafes, and people going about their daily lives.</li><li><strong>Leyn Baan Street:</strong> Quieter residential area with beautiful colonial houses.</li><li><strong>Market Areas:</strong> Capture the local vendors and daily commerce.</li></ul><h3>Photography Tips</h3><p>To get the best shots in Galle Fort:</p><ul><li>Visit early morning or late afternoon for the best light</li><li>Use a wide-angle lens for architectural shots</li><li>Look for interesting shadows and reflections</li><li>Be respectful when photographing people - always ask permission</li><li>Consider the weather - overcast days can be great for architectural photography</li></ul><p>Don''t forget to explore the lesser-known corners of the fort, where you might discover hidden gems and unique perspectives that others miss.</p>', '/images/galle-photography-1.jpg', 'Dutch Wall Fort Team', true, NOW() - INTERVAL ''3 days'', 4)
ON CONFLICT (slug) DO NOTHING;
