services:
  postgres:
    image: postgres:16-alpine
    container_name: dutchwallfort-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dutchwallfort
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/init/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dutchwallfort-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dutchwallfort
      - NODE_ENV=development
      - JWT_SECRET=dutchwallfort-super-secret-jwt-key-change-in-production-2024
      - MAILJET_API_KEY=38c3f40fd32cc60609b83233d87e93a9
      - MAILJET_SECRET_KEY=fe3259ed3c40a1ad3c85c6551687ed5f
      - MAILJET_FROM_EMAIL=support@dutchwallfort.com
      - ADMIN_EMAIL=reservations@dutchwallfort.com
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dutchwallfort-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
    driver: local